{
 "title": "Logs Dashboard",
 "tags": [
  "go-observability-lab",
  "logs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "5xx log rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({service=\"app\"} | json | status>=500 [5m]))"
    }
   ]
  },
  {
   "title": "Request rate by route (from logs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (route) (rate({service=\"app\"} | json | __error__=\"\" [5m]))"
    }
   ]
  },
  {
   "title": "Application errors",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"app\"} | json | level=\"ERROR\""
    }
   ]
  }
 ]
}